-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.softcartdimcategory
(
    categoryid integer NOT NULL,
    categoryname character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT softcartdimcategory_pkey PRIMARY KEY (categoryid)
);

CREATE TABLE IF NOT EXISTS public.softcartdimcountry
(
    countryid integer NOT NULL,
    countryname character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT softcartdimcountry_pkey PRIMARY KEY (countryid)
);

CREATE TABLE IF NOT EXISTS public.softcartdimdate
(
    dateid integer NOT NULL,
    month integer,
    monthname character varying(20) COLLATE pg_catalog."default",
    year integer,
    day integer,
    weekday integer,
    weekdayname character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT softcartdimdate_pkey PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS public.softcartdimitem
(
    itemid integer NOT NULL,
    itemname character varying(255) COLLATE pg_catalog."default",
    categoryid integer,
    CONSTRAINT softcartdimitem_pkey PRIMARY KEY (itemid)
);

CREATE TABLE IF NOT EXISTS public.softcartfactsales
(
    salesid integer NOT NULL,
    dateid integer,
    orderid integer,
    itemid integer,
    quantity integer,
    price numeric(10, 2),
    total numeric(10, 2),
    countryid integer,
    CONSTRAINT softcartfactsales_pkey PRIMARY KEY (salesid)
);

ALTER TABLE IF EXISTS public.softcartdimitem
    ADD CONSTRAINT softcartdimitem_categoryid_fkey FOREIGN KEY (categoryid)
    REFERENCES public.softcartdimcategory (categoryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.softcartfactsales
    ADD CONSTRAINT softcartfactsales_countryid_fkey FOREIGN KEY (countryid)
    REFERENCES public.softcartdimcountry (countryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.softcartfactsales
    ADD CONSTRAINT softcartfactsales_dateid_fkey FOREIGN KEY (dateid)
    REFERENCES public.softcartdimdate (dateid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.softcartfactsales
    ADD CONSTRAINT softcartfactsales_itemid_fkey FOREIGN KEY (itemid)
    REFERENCES public.softcartdimitem (itemid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;